### ISSUE TITLE
two errors with refine, meta and flatten

### ISSUE THREAD

**Issue by Alexis-Martin** [saucisson/lua-layeredata#11]
example is better than explication so...

    local Layer = require "layeredata"
    local layer = Layer.new {
      name = "layer",
    }
    local _  = Layer.reference "layer_label"
    layer.__meta__ = {
      __label__ = "layer_label",
      layer_type = {
        first_type = { id = "first_type_id" },
      },

      second_type = {
        __refines__ = { _.layer_type },
      }
    }
    do
      local flat = Layer.flatten(layer)
      print(Layer.dump(flat, true))
      print(flat.a.second_type.first_type.id)
    end

when I run this code, `dump` print something wrong because `second_type = {}` and `print(flat.a.second_type.first_type.id)` create an error.

if I change this line `layer.__meta__ = {` by `layer.x = {` it works. 

But, in this case, if I change `print(Layer.dump(flat, true))` by `print(Layer.dump(flat, false))` there is another error.

**Comment by saucisson** [comment]
Try with the update, please.
