### ISSUE TITLE
__default__

### ISSUE THREAD

**Issue by Alexis-Martin** [saucisson/lua-layeredata#13]
how do we do `__default__` key ?
like this ? :

    local Layer = require "layeredata"
    local layer = Layer.new { name = "A" }
    local _     = Layer.reference "A"

    layer.A = {
      __label__ = "A",
      A_type = {
        id = 3,
      },
      A_collection = {
        __default__ = {
          __refines__ = {
            _.A_type,
          }
        }
      }
    }

or just : 

       A_collection = {
        __default__ = {
          _.A_type,
        }
      }

**Comment by saucisson** [comment]
Short answer:

````lua
__default__ = {
      __refines__ = {
        _.A_type,
      }
    }
````

**Comment by Alexis-Martin** [comment]
local Layer = require "layeredata"
    local layer = Layer.new { name = "A" }
    local _     = Layer.reference "A"

    layer.A = {
      __label__ = "A",
      A_type = {
        id = 1,
      },
      B_collection = {
        __default__ = {
          __refines__ = {
            _.A_type,
          },
        },
        X = {},
      }
    }
    print(Layer.dump(Layer.flatten(layer)))

`X`doesn't refine A_type and doesn't have `id = 1`.
