### ISSUE TITLE
collection where keys are reference

### ISSUE THREAD

**Issue by Alexis-Martin** [saucisson/lua-layeredata#15]
Is it possible for keys to be references? 

If I do : 

    local Layer = require "layeredata"
    local layer = Layer.new {
      name = "A",
    }
    local _    = Layer.reference "A"

    layer.A = {
      __label__ = "A",
      A_collection = {
        X = {},
      },
      B_collection = {
        [_.A_collection.X] = 3,
      }
    }
    print(Layer.dump(Layer.flatten(layer)))

`B_collection` is empty.

If I remove brackets I have a lua error.

**Comment by saucisson** [comment]
Please first install a fork of serpent: https://github.com/saucisson/serpent.git (awaiting serpent to fix the keys serialization).
