### ISSUE TITLE
error with absolute reference

### ISSUE THREAD

**Issue by Alexis-Martin** [saucisson/lua-layeredata#16]
When I do that, the `__refines__` is empty and there is no `id` in `A` : 

    local Layer = require "layeredata"
    local form  = Layer.new { name = "formalism" }
    local model = Layer.new { name = "model" }
    local root  = Layer.reference (false)

    form.__meta__ = {
      form_type = {
        id = 1,
      }
    }  

    model.__depends__ = {
      form,
    }
    model.model = {
      A = {
        __refines__ = {
          root.__meta__.form_type,
        }
      }
    }
    do
      print(Layer.dump(Layer.flatten(model)))
    end

**Comment by saucisson** [comment]
On my computer it returns:

````lua
do local _ = {
  __meta__ = {
    form_type = {
      id = 1
    }
  },
  model = {
    A = {
      __refines__ = {
        "false -> [__meta__] [form_type]"
      },
      id = 1
    }
  }
}
return _
end
````

**Comment by Alexis-Martin** [comment]
I try with the update and I have this result : 

    do local _ = {
      model = {
        A = {
          __refines__ = {}
        }
      }
    }
    return _
    end

And `print(model.model.A.id)` returns `nil`

**Comment by saucisson** [comment]
Strange behavior. We will look at it next time we meet ;-)

**Comment by saucisson** [comment]
Was caused by `c3` library.
