### ISSUE TITLE
Unexpected error when iterating on the leaves of a formalism

### ISSUE THREAD

**Issue by hle35** [saucisson/lua-layeredata#47]
When running the code   [https://github.com/hle35/palette/blob/dev/src/cosy/tool/palette.lua]
 we got the following error message :
/home/cosy/cosyserver/share/lua/5.2/cosy/tool/palette.lua:28: bad argument #1 to 'pairs' (table expected, got nil)	thread: 0x20a1e40	nil

**Comment by saucisson** [comment]
Merged with #46
