### ISSUE TITLE
relative path

### ISSUE THREAD

**Issue by Alexis-Martin** [saucisson/lua-layeredata#5]
Add an __id__ key like this

    local Proxy = require "layeredata"
    local layer = Proxy.new { 
      name = "relative path example",
    }
    local _     = Proxy.placeholder

    layer.__meta__ = {
      relative_type = {
        __id__ = "myid",
        
        __meta__ = {
          A_type = {},
          
          B_type = {
            content_type    = (_ "myid").__meta__.A_type,
          },
        },
      },
    }

**Comment by saucisson** [comment]
Instead of `__id__`, i propose `__label__`.

**Comment by saucisson** [comment]
Fixed in 1ae65a26534fd500ff2f1dc2241fb83ad986458b
