### ISSUE TITLE
default value

### ISSUE THREAD

**Issue by Alexis-Martin** [saucisson/lua-layeredata#6]
it could be great to have default in table like that for example:

    local Proxy = require "layeredata"
    local layer = Proxy.new { 
      name = "default value example",
    }
    local _     = Proxy.placeholder

    layer.__meta__ = {
      default_type = {
        __meta__ = {
          A_type = {}
        },
        
        A = {
          __default__ = {
            content_type = _.__meta__.default_type.__meta__.A_type,
          },
        },
      },
    }

**Comment by saucisson** [comment]
Fixed in 124b4df35d68f48c7ab97e940fc8acac84308b63
