### ISSUE TITLE
Add key __checks__

### ISSUE THREAD

**Issue by Alexis-Martin** [saucisson/lua-layeredata#9]
We need to apply checks when we refine a type. Checks may be defined in a specific type like that:

    Layer = require "layeredata"
    layer = Layer.new{ name = "layer" }

    Layer = require "layeredata"
    layer = Layer.new{ name = "layer" }

    layer.__meta__ = {
      layer_type = {
        __meta__ = {
          ...,
          __checks__ = {
            function (parameter) 
              ...
            end
          },
        },
      },
    }

and apply to an element when it refines this specific type

    a = {
      __meta__ = {
        content_type = layer_type,
      },
      x = {
        __refines__ = {
          layer_type,
        },
        ...
      },
    },

Here we would like apply to `x` the checks defined in `layer_type`

**Comment by Alexis-Martin** [comment]
local Layer = require "layeredata"
    local layer = Layer.new {
      name = "A",
    }
    local _     = Layer.reference "A"
    local root  = Layer.reference (false)

    layer.A = {
      __label__ = "A",

      A_type = {
        __checks__ = {
          function ()
            return "warning"
          end
        }
      },

      B = {
        __refines__ = {
          _.A_type
        },
      }
    }
    print(Layer.dump(Layer.flatten(layer)))

**Comment by saucisson** [comment]
Please try with the following code and the latest update:

````lua
    local Layer = require "layeredata"
    local layer = Layer.new {
      name = "A",
    }
    local _     = Layer.reference "A"

    layer.A = {
      __label__ = "A",

      A_type = {
        __checks__ = {
          function (proxy)
            if not proxy.C then
              return "warning"
            end
          end
        }
      },
      B = {
        __refines__ = {
          _.A_type
        },
        C = 3
      },
      D = {
        __refines__ = {
          _.A_type
        },
      },
    }

    print (layer.A.B)
    print (layer.A.D)
    print (Layer.dump (Layer.flatten (layer)))
````

**Comment by Alexis-Martin** [comment]
It works! 
congratulation!

**Comment by saucisson** [comment]
So happy!
